### ISSUE TITLE
Replace the temporary logo with a proper one for release

### ISSUE THREAD

**Issue by Twixes** [PostHog/downsampling-plugin#4]
We'll want to add this to the official [plugin repository](https://github.com/PostHog/plugin-repository) and publish in PostHog Cloud, but we can't have a logo with a Shutterstock watermark for that. May be good to request a design from Lottie.

**Comment by lottiecoxon** [comment]
![Untitled_Artwork 254](https://user-images.githubusercontent.com/65415371/118508432-1b9fd800-b727-11eb-80d1-38abc76f2a33.jpg)

**Comment by lottiecoxon** [comment]
working on this - this week :)

**Comment by neilkakkar** [comment]
Nice, love the concept, makes a lot of sense :D

**Comment by lottiecoxon** [comment]
![Frame 7856](https://user-images.githubusercontent.com/65415371/119325494-d3c60700-bc78-11eb-98ce-6cbcea3a08e8.png)
how is this?

**Comment by neilkakkar** [comment]
Looks good to me 👍  - is there a slightly bigger version I can use for the repo, so that it doesn't seem pixelated?

**Comment by lottiecoxon** [comment]
yes sorry!

**Comment by lottiecoxon** [comment]
![Frame 7856](https://user-images.githubusercontent.com/65415371/119529194-ca709380-bd79-11eb-8749-99848d42cb44.png)
